language: node_js
sudo: enabled
notifications:
  email: false
  #slack: ${slack_acc}:${slack_token}
  slack: bull-and-cat:byDRDQP20Rm69PyAvWADvKL6
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
    on_pull_requests: always
branches:
  only:
  - master
  - /^(feature|fix)-.*$/
node_js:
  - "8.11.4"
before_install:
  - npm install -g serverless && serverless --version
  - serverless config credentials -p aws -k ${aws_access_key_id} -s ${aws_secret_access_key}
install:
before_script:
script:
  - echo "----LS current folder-----" && ls -la
  - echo "----Print current path----" && pwd
  - serverless package
  - serverless deploy
  - serverless info
  