language: node_js
sudo: enabled
branches:
  only:
  - master
  - /^(feature|fix)-.*$/
node_js:
  - "8.11.4"
before_install:
  - npm install -g serverless && serverless --version
  - serverless config credentials -p aws -k ${aws_access_key_id} -s ${aws_secret_access_key}
install:
before_script:
script:
  - echo "----LS current folder-----" && ls -la
  - echo "----Print current path----" && pwd
  - serverless info
